Informative Clauses
SMPTE/html-pub pull request #136
Opened 2023-06-30 22:54 UTC by SteveLLamb

Add ` (Informative)` text to clauses

2025-05-16 17:02 UTC, SteveLLamb commented
This is per request on late comments for editorials updates on a DP ballot by @ERyan71258

2025-05-16 17:06 UTC, palemieux requested changes
Informative elements should be indicated using `class="informative"` just as appendices are signaled using `class="appendix"`.

2025-05-16 17:34 UTC, SteveLLamb commented
> Informative elements should be indicated using `class="informative"` just as appendices are signaled using `class="appendix"`.

update to using class in https://github.com/SMPTE/html-pub/pull/136/commits/0da2ce01109fbabde579cfe13d09aab82e8e0f2a

2025-05-16 19:15 UTC, ERyan71258 commented
Would an editor also be able to add "(Normative)" to an annex title? Per ISO, an annex must be specified as either Normative or Informative.

2025-05-16 19:32 UTC, SteveLLamb commented
> Would an editor also be able to add "(Normative)" to an annex title? Per ISO, an annex must be specified as either Normative or Informative.

@ERyan71258 I changed the logic to default to putting "(Normative)" unless declared "informative" in https://github.com/SMPTE/html-pub/pull/136/commits/1b7f1c6ce1c483e5cf33449c2307d680ec4ce70a

2025-05-19 20:03 UTC, ERyan71258 approved these changes

2025-05-19 20:14 UTC, merged